/**
 * Kudos catalogue. One place, served to the web app through the wrap-up
 * payload (the picker) and the public profile endpoint (the shelf), so the
 * client never carries its own copy of the labels.
 *
 * The tags are deliberately universal across hobbies and read as props
 * rather than ratings: nothing here can be read as a mark against someone.
 * Wording chosen by Rob, 2026-09-06, extended the same evening to 64 tags then 79 with a Magic-flavoured batch, then 106 on 2026-09-07 and 201 on 2026-09-12
 * ("Sweaty", "Salt Miner" and friends are in-jokes his crowd uses). Users
 * see these as "tags"; kudos stays the internal name (table, routes,
 * preference key). The picker sorts alphabetically and has a search box,
 * so definition order here does not matter. Slugs are stable once shipped:
 * they are stored on kudos rows.
 */
export const KUDOS_TAGS = [
  { tag: "good_energy", label: "Good Energy", emoji: "⚡" },
  { tag: "quick_wit", label: "Quick Wit", emoji: "😏" },
  { tag: "banter_merchant", label: "Banter Merchant", emoji: "🗣️" },
  { tag: "social_glue", label: "Social Glue", emoji: "🧲" },
  { tag: "side_quest_energy", label: "Side-Quest Energy", emoji: "🗺️" },
  { tag: "good_sport", label: "Good Sport", emoji: "🤝" },
  { tag: "knows_cool_stuff", label: "Knows Cool Stuff", emoji: "🧠" },
  { tag: "great_taste", label: "Great Taste", emoji: "👌" },
  { tag: "refreshingly_normal", label: "Refreshingly Normal", emoji: "😌" },
  { tag: "delightfully_unhinged", label: "Delightfully Unhinged", emoji: "🤪" },
  { tag: "weird_in_a_good_way", label: "Weird in a Good Way", emoji: "🦄" },
  { tag: "glad_you_came", label: "Glad You Came", emoji: "🎉" },
  { tag: "would_hang_again", label: "Would Hang Again", emoji: "🔁" },
  { tag: "would_recommend", label: "Would Recommend", emoji: "⭐" },
  { tag: "group_mvp", label: "Group MVP", emoji: "🏆" },
  { tag: "hype_person", label: "Hype Person", emoji: "📣" },
  { tag: "comedy_relief", label: "Comedy Relief", emoji: "🎭" },
  { tag: "laughs_at_their_own_jokes", label: "Laughs at Their Own Jokes", emoji: "🤭" },
  { tag: "instigator", label: "Instigator", emoji: "🧨" },
  { tag: "plot_complicator", label: "Plot Complicator", emoji: "🌀" },
  { tag: "dangerously_persuasive", label: "Dangerously Persuasive", emoji: "🪄" },
  { tag: "terrible_influence", label: "Terrible Influence", emoji: "😈" },
  { tag: "makes_plans_happen", label: "Makes Plans Happen", emoji: "📅" },
  { tag: "built_for_shenanigans", label: "Built for Shenanigans", emoji: "🐒" },
  { tag: "brought_snacks", label: "Brought Snacks", emoji: "🍿" },
  { tag: "knows_a_guy", label: "Knows a Guy", emoji: "🕶️" },
  { tag: "reads_the_instructions", label: "Reads the Instructions", emoji: "📖" },
  { tag: "actually_made_a_reservation", label: "Actually Made a Reservation", emoji: "📞" },
  { tag: "functional_adult", label: "Functional Adult", emoji: "🧾" },
  { tag: "problem_solver", label: "Problem Solver", emoji: "🔧" },
  { tag: "hot_take_machine", label: "Hot Take Machine", emoji: "🌶️" },
  { tag: "never_boring", label: "Never Boring", emoji: "🎢" },
  { tag: "makes_you_think", label: "Makes You Think", emoji: "💭" },
  { tag: "strong_opinions", label: "Strong Opinions", emoji: "📢" },
  { tag: "excellent_rant", label: "Excellent Rant", emoji: "🎙️" },
  { tag: "shows_up", label: "Shows Up", emoji: "📍" },
  { tag: "came_in_clutch", label: "Came in Clutch", emoji: "🎯" },
  { tag: "solid_human", label: "Solid Human", emoji: "🪨" },
  { tag: "good_under_pressure", label: "Good Under Pressure", emoji: "🧊" },
  { tag: "actually_helps", label: "Actually Helps", emoji: "🙌" },
  { tag: "trusted_with_the_keys", label: "Trusted With the Keys", emoji: "🔑" },
  { tag: "feeds_the_group", label: "Feeds the Group", emoji: "🍕" },
  { tag: "host_energy", label: "Host Energy", emoji: "🏠" },
  { tag: "table_captain", label: "Table Captain", emoji: "🧭" },
  { tag: "elite_host", label: "Elite Host", emoji: "👑" },
  { tag: "rules_lawyer", label: "Rules Lawyer", emoji: "⚖️" },
  { tag: "rng_god", label: "RNG God", emoji: "🎲" },
  { tag: "tactical_menace", label: "Tactical Menace", emoji: "♟️" },
  { tag: "table_politician", label: "Table Politician", emoji: "🗳️" },
  { tag: "button_pusher", label: "Button Pusher", emoji: "🔘" },
  { tag: "analysis_paralysis", label: "Analysis Paralysis", emoji: "⏳" },
  { tag: "salt_miner", label: "Salt Miner", emoji: "🧂" },
  { tag: "selective_hearing", label: "Selective Hearing", emoji: "🙉" },
  { tag: "needs_adult_supervision", label: "Needs Adult Supervision", emoji: "🚸" },
  { tag: "suspicious_character", label: "Suspicious Character", emoji: "🕵️" },
  { tag: "cannot_be_taken_anywhere", label: "Cannot Be Taken Anywhere", emoji: "🚫" },
  { tag: "menace", label: "Menace", emoji: "😼" },
  { tag: "enabler", label: "Enabler", emoji: "🍻" },
  { tag: "wildcard", label: "Wildcard", emoji: "🃏" },
  { tag: "brain_cell", label: "Brain Cell", emoji: "💡" },
  { tag: "good_egg", label: "Good Egg", emoji: "🥚" },
  { tag: "absolute_unit", label: "Absolute Unit", emoji: "🐂" },
  { tag: "topdeck_hero", label: "Topdeck Hero", emoji: "🎴" },
  { tag: "reads_the_card_eventually", label: "Reads the Card Eventually", emoji: "🔍" },
  { tag: "brewer", label: "Brewer", emoji: "🧪" },
  { tag: "had_the_answer", label: "Had the Answer", emoji: "🛡️" },
  { tag: "keeps_sketchy_hands", label: "Keeps Sketchy Hands", emoji: "🤞" },
  { tag: "misplays_with_confidence", label: "Misplays With Confidence", emoji: "😎" },
  { tag: "combo_player", label: "Combo Player", emoji: "🔗" },
  { tag: "board_wipe_enthusiast", label: "Board Wipe Enthusiast", emoji: "💥" },
  { tag: "says_in_response", label: "Says \"In Response\"", emoji: "✋" },
  { tag: "haste_enjoyer", label: "Haste Enjoyer", emoji: "💨" },
  { tag: "timmy_energy", label: "Timmy Energy", emoji: "🦖" },
  { tag: "control_player", label: "Control Player", emoji: "❄️" },
  { tag: "storm_brain", label: "Storm Brain", emoji: "⛈️" },
  { tag: "midrange_enjoyer", label: "Midrange Enjoyer", emoji: "🎚️" },
  { tag: "aggro_brain", label: "Aggro Brain", emoji: "🔥" },
  { tag: "mulligan_magnet", label: "Mulligan Magnet", emoji: "🔄" },
  { tag: "card_shark", label: "Card Shark", emoji: "🦈" },
  { tag: "sleeper_threat", label: "Sleeper Threat", emoji: "😴" },
  { tag: "public_enemy", label: "Public Enemy", emoji: "🚨" },
  { tag: "no_fear", label: "No Fear", emoji: "🦁" },
  { tag: "group_historian", label: "Group Historian", emoji: "📜" },
  { tag: "human_gps", label: "Human GPS", emoji: "🛰️" },
  { tag: "always_prepared", label: "Always Prepared", emoji: "🎒" },
  { tag: "herds_cats", label: "Herds Cats", emoji: "🐈" },
  { tag: "keeps_the_peace", label: "Keeps the Peace", emoji: "🕊️" },
  { tag: "perfect_curve", label: "Perfect Curve", emoji: "📈" },
  { tag: "bad_beats", label: "Bad Beats", emoji: "🎰" },
  { tag: "emergency_contact", label: "Emergency Contact", emoji: "🆘" },
  { tag: "the_regular", label: "The Regular", emoji: "🪑" },
  { tag: "local_expert", label: "Local Expert", emoji: "🏙️" },
  { tag: "group_treasurer", label: "Group Treasurer", emoji: "💰" },
  { tag: "makes_the_playlist", label: "Makes the Playlist", emoji: "🎧" },
  { tag: "makes_the_decision", label: "Makes the Decision", emoji: "✅" },
  { tag: "never_forgets_a_face", label: "Never Forgets a Face", emoji: "👀" },
  { tag: "always_on_time", label: "Always on Time", emoji: "⏰" },
  { tag: "stays_till_the_end", label: "Stays Till the End", emoji: "🌙" },
  { tag: "first_to_volunteer", label: "First to Volunteer", emoji: "🙋" },
  { tag: "takes_one_for_the_team", label: "Takes One for the Team", emoji: "🫡" },
  { tag: "asks_the_good_question", label: "Asks the Good Question", emoji: "❓" },
  { tag: "remembers_what_you_said", label: "Remembers What You Said", emoji: "📝" },
  { tag: "carries_the_conversation", label: "Carries the Conversation", emoji: "🎤" },
  { tag: "keeps_everyone_posted", label: "Keeps Everyone Posted", emoji: "📬" },

  // ── Added 2026-09-12: short, generic person-descriptors in the register
  //    of Absolute Unit and Solid Human, plus a batch of affectionate jabs.
  //    Wording picked by Rob from three rounds of suggestions.
  { tag: "actually_listens", label: "Actually Listens", emoji: "👂" },
  { tag: "talks_to_everyone", label: "Talks to Everyone", emoji: "🫱" },
  { tag: "patient_with_beginners", label: "Patient With Beginners", emoji: "🐣" },
  { tag: "explains_it_well", label: "Explains It Well", emoji: "🎓" },
  { tag: "zero_small_talk", label: "Zero Small Talk", emoji: "⏭️" },
  { tag: "best_story_of_the_night", label: "Best Story of the Night", emoji: "🎞️" },
  { tag: "dad_jokes_only", label: "Dad Jokes Only", emoji: "👔" },
  { tag: "quietly_excellent", label: "Quietly Excellent", emoji: "🤫" },
  { tag: "punches_above_their_weight", label: "Punches Above Their Weight", emoji: "🥊" },
  { tag: "somehow_always_wins", label: "Somehow Always Wins", emoji: "🍀" },
  { tag: "zero_impulse_control", label: "Zero Impulse Control", emoji: "🛒" },
  { tag: "yes_and_energy", label: "Yes-And Energy", emoji: "🙆" },
  { tag: "five_minutes_away", label: "Five Minutes Away", emoji: "⏱️" },
  { tag: "fashionably_late", label: "Fashionably Late", emoji: "🕰️" },
  { tag: "ghost_exit", label: "Ghost Exit", emoji: "🚪" },
  { tag: "long_goodbye", label: "Long Goodbye", emoji: "👋" },
  { tag: "muted_the_group_chat", label: "Muted the Group Chat", emoji: "🔕" },
  { tag: "lurker", label: "Lurker", emoji: "🫥" },
  { tag: "would_rather_be_home", label: "Would Rather Be Home", emoji: "🛋️" },
  { tag: "only_here_for_the_snacks", label: "Only Here for the Snacks", emoji: "🍟" },
  { tag: "just_one_more_game", label: "Just One More Game", emoji: "🕐" },
  { tag: "main_character_energy", label: "Main Character Energy", emoji: "🎬" },
  { tag: "tells_the_same_story", label: "Tells the Same Story", emoji: "🔂" },
  { tag: "never_lets_it_go", label: "Never Lets It Go", emoji: "🪢" },
  { tag: "speaks_in_references", label: "Speaks in References", emoji: "🎥" },
  { tag: "fact_checker", label: "Fact Checker", emoji: "🔎" },
  { tag: "conspiracy_corner", label: "Conspiracy Corner", emoji: "🛸" },
  { tag: "has_one_topic", label: "Has One Topic", emoji: "📻" },
  { tag: "devils_advocate", label: "Devil's Advocate", emoji: "🗯️" },
  { tag: "no_poker_face", label: "No Poker Face", emoji: "🫣" },
  { tag: "loud_whisperer", label: "Loud Whisperer", emoji: "🔊" },
  { tag: "always_cold", label: "Always Cold", emoji: "🥶" },
  { tag: "big_reactions", label: "Big Reactions", emoji: "😱" },
  { tag: "all_the_gear_no_idea", label: "All the Gear, No Idea", emoji: "🛠️" },
  { tag: "new_hobby_every_month", label: "New Hobby Every Month", emoji: "🪃" },
  { tag: "watched_a_tutorial_once", label: "Watched a Tutorial Once", emoji: "📺" },
  { tag: "two_drinks_in", label: "Two Drinks In", emoji: "🍷" },
  { tag: "absolute_legend", label: "Absolute Legend", emoji: "🏅" },
  { tag: "absolute_sweetheart", label: "Absolute Sweetheart", emoji: "🍬" },
  { tag: "the_anchor", label: "The Anchor", emoji: "⚓" },
  { tag: "the_backbone", label: "The Backbone", emoji: "🦴" },
  { tag: "the_oracle", label: "The Oracle", emoji: "🔮" },
  { tag: "the_machine", label: "The Machine", emoji: "🤖" },
  { tag: "good_people", label: "Good People", emoji: "👥" },
  { tag: "real_one", label: "Real One", emoji: "💯" },
  { tag: "ol_reliable", label: "Ol' Reliable", emoji: "🪛" },
  { tag: "safe_pair_of_hands", label: "Safe Pair of Hands", emoji: "🧤" },
  { tag: "national_treasure", label: "National Treasure", emoji: "🏛️" },
  { tag: "local_legend", label: "Local Legend", emoji: "🏘️" },
  { tag: "ride_or_die", label: "Ride or Die", emoji: "🏍️" },
  { tag: "good_hang", label: "Good Hang", emoji: "🤙" },
  { tag: "golden_retriever_energy", label: "Golden Retriever Energy", emoji: "🐕" },
  { tag: "low_maintenance", label: "Low Maintenance", emoji: "🪴" },
  { tag: "unbothered", label: "Unbothered", emoji: "🧘" },
  { tag: "chaotic_good", label: "Chaotic Good", emoji: "😇" },
  { tag: "chaotic_neutral", label: "Chaotic Neutral", emoji: "🌗" },
  { tag: "built_different", label: "Built Different", emoji: "🏗️" },
  { tag: "top_tier", label: "Top Tier", emoji: "🔝" },
  { tag: "zero_ego", label: "Zero Ego", emoji: "🪶" },
  { tag: "zero_filter", label: "Zero Filter", emoji: "🚱" },
  { tag: "big_laugh", label: "Big Laugh", emoji: "😂" },
  { tag: "live_wire", label: "Live Wire", emoji: "🔌" },
  { tag: "force_of_nature", label: "Force of Nature", emoji: "🌪️" },
  { tag: "chaos_coordinator", label: "Chaos Coordinator", emoji: "🎪" },
  { tag: "morale_officer", label: "Morale Officer", emoji: "🎖️" },
  { tag: "group_mascot", label: "Group Mascot", emoji: "🐻" },
  { tag: "deeply_unserious", label: "Deeply Unserious", emoji: "🎈" },
  { tag: "certified_gremlin", label: "Certified Gremlin", emoji: "👺" },
  { tag: "quietly_feral", label: "Quietly Feral", emoji: "🐺" },
  { tag: "unreliable_narrator", label: "Unreliable Narrator", emoji: "📕" },
  { tag: "loose_cannon", label: "Loose Cannon", emoji: "💣" },
  { tag: "chronically_online", label: "Chronically Online", emoji: "📱" },
  { tag: "touch_grass_candidate", label: "Touch Grass Candidate", emoji: "🌱" },
  { tag: "professional_yapper", label: "Professional Yapper", emoji: "💬" },
  { tag: "big_softie", label: "Big Softie", emoji: "🧸" },
  { tag: "takes_a_joke", label: "Takes a Joke", emoji: "😄" },
  { tag: "dishes_it_out", label: "Dishes It Out", emoji: "🍽️" },

  // ── Added 2026-09-12: plain adjectives. The catalogue was long on
  //    characters and jokes and short on the simple neutral-to-positive
  //    words people reach for first (Rob).
  { tag: "super_friendly", label: "Super Friendly", emoji: "😃" },
  { tag: "reliable", label: "Reliable", emoji: "🧱" },
  { tag: "well_mannered", label: "Well Mannered", emoji: "🎩" },
  { tag: "extra_polite", label: "Extra Polite", emoji: "🙏" },
  { tag: "always_positive", label: "Always Positive", emoji: "🌞" },
  { tag: "chill", label: "Chill", emoji: "🌴" },
  { tag: "genuine", label: "Genuine", emoji: "🤍" },
  { tag: "easygoing", label: "Easygoing", emoji: "🍃" },
  { tag: "thoughtful", label: "Thoughtful", emoji: "🕊" },
  { tag: "generous", label: "Generous", emoji: "🎁" },
  { tag: "welcoming", label: "Welcoming", emoji: "🤗" },
  { tag: "warm", label: "Warm", emoji: "☀️" },
  { tag: "funny", label: "Funny", emoji: "😆" },
  { tag: "kind", label: "Kind", emoji: "💛" },
  { tag: "honest", label: "Honest", emoji: "📐" },
  { tag: "humble", label: "Humble", emoji: "🙇" },
  { tag: "curious", label: "Curious", emoji: "🔭" },
  { tag: "creative", label: "Creative", emoji: "🎨" },
  { tag: "encouraging", label: "Encouraging", emoji: "👏" },
  { tag: "down_to_earth", label: "Down to Earth", emoji: "🌍" },
] as const;

export type KudosTag = (typeof KUDOS_TAGS)[number]["tag"];

const BY_TAG = new Map<string, (typeof KUDOS_TAGS)[number]>(KUDOS_TAGS.map((t) => [t.tag, t]));

export function isKudosTag(value: unknown): value is KudosTag {
  return typeof value === "string" && BY_TAG.has(value);
}

export function kudosTagInfo(tag: string): (typeof KUDOS_TAGS)[number] | null {
  return BY_TAG.get(tag) ?? null;
}

/** Each giver hands out at most this many kudos per plan. Keeps them scarce
 *  enough to mean something and stops a table of eight from awarding
 *  everyone everything. */
export const KUDOS_MAX_PER_PLAN = 3;

/** Kudos can be given for a week after the plan starts, the same window the
 *  wrap-up card already uses. */
export const KUDOS_WINDOW_MS = 7 * 24 * 60 * 60 * 1000;

