-- Migration 124: Community access gets a third mode, "invite only".
--
-- join_mode 'invite_only' communities are hidden from the directory and search,
-- and people join instantly with the community's invite link (no approval).
-- The invite code is generated by the API when a community switches into
-- invite-only mode and can be reset by the owner; old links stop working.
--
-- Run: psql "$DATABASE_URL" -f web/sql/124_community_invite_only.sql

ALTER TABLE newchums.communities DROP CONSTRAINT IF EXISTS communities_join_mode_check;
ALTER TABLE newchums.communities
  ADD CONSTRAINT communities_join_mode_check
  CHECK (join_mode IN ('open', 'approval_required', 'invite_only'));

ALTER TABLE newchums.communities ADD COLUMN IF NOT EXISTS invite_code TEXT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_communities_invite_code
  ON newchums.communities (invite_code) WHERE invite_code IS NOT NULL;

COMMENT ON COLUMN newchums.communities.invite_code IS 'Secret for the invite link of an invite-only community; NULL until the mode is first used. Reset by the owner.';
