name = "newchums-api"
main = "src/index.ts"
compatibility_date = "2026-02-09"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
APP_ENV = "production"
EMAIL_FROM = "NewChums <no-reply@ourmodule.com>"
WEB_BASE_URL = "https://newchums.com"
POSTMARK_TEMPLATE_VERIFY = "43483393"
POSTMARK_TEMPLATE_RESET  = "43483403"
POSTMARK_TEMPLATE_RSVP   = "43483423"
AXIOM_DATASET = "newchums-api"

[env.preview.vars]
APP_ENV = "preview"
EMAIL_FROM = "NewChums <no-reply@ourmodule.com>"
WEB_BASE_URL = "https://newchums.com"
POSTMARK_TEMPLATE_VERIFY = "43483393"
POSTMARK_TEMPLATE_RESET = "43483403"
POSTMARK_TEMPLATE_RSVP = "43483423"
AXIOM_DATASET = "newchums-api"

[env.production.vars]
APP_ENV = "production"
EMAIL_FROM = "NewChums <no-reply@ourmodule.com>"
WEB_BASE_URL = "https://newchums.com"
POSTMARK_TEMPLATE_VERIFY = "43483393"
POSTMARK_TEMPLATE_RESET = "43483403"
POSTMARK_TEMPLATE_RSVP = "43483423"
AXIOM_DATASET = "newchums-api"
